/*
 *
 *    Copyright (c) 2021 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#ifndef CHIP_STRUCTS_H
#define CHIP_STRUCTS_H

#import <Foundation/Foundation.h>

@interface CHIPScenesClusterSceneExtensionFieldSet : NSObject
@property (copy) NSNumber * _Nonnull ClusterId;
@property (copy) NSNumber * _Nonnull Length;
@property (copy) NSNumber * _Nonnull Value;
@end

@interface CHIPPowerProfileClusterPowerProfileRecord : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull EnergyPhaseId;
@property (copy) NSNumber * _Nonnull PowerProfileRemoteControl;
@property (copy) NSNumber * _Nonnull PowerProfileState;
@end

@interface CHIPPowerProfileClusterScheduledPhase : NSObject
@property (copy) NSNumber * _Nonnull EnergyPhaseId;
@property (copy) NSNumber * _Nonnull ScheduledTime;
@end

@interface CHIPPowerProfileClusterTransferredPhase : NSObject
@property (copy) NSNumber * _Nonnull EnergyPhaseId;
@property (copy) NSNumber * _Nonnull MacroPhaseId;
@property (copy) NSNumber * _Nonnull ExpectedDuration;
@property (copy) NSNumber * _Nonnull PeakPower;
@property (copy) NSNumber * _Nonnull Energy;
@property (copy) NSNumber * _Nonnull MaxActivationDelay;
@end

@interface CHIPDescriptorClusterDeviceType : NSObject
@property (copy) NSNumber * _Nonnull Type;
@property (copy) NSNumber * _Nonnull Revision;
@end

@interface CHIPBridgedActionsClusterActionStruct : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSString * _Nonnull Name;
@property (copy) NSNumber * _Nonnull Type;
@property (copy) NSNumber * _Nonnull EndpointListID;
@property (copy) NSNumber * _Nonnull SupportedCommands;
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPBridgedActionsClusterEndpointListStruct : NSObject
@property (copy) NSNumber * _Nonnull EndpointListID;
@property (copy) NSString * _Nonnull Name;
@property (copy) NSNumber * _Nonnull Type;
@property (copy) NSData * _Nonnull Endpoints;
@end

@interface CHIPGeneralCommissioningClusterBasicCommissioningInfoType : NSObject
@property (copy) NSNumber * _Nonnull FailSafeExpiryLengthMs;
@end

@interface CHIPNetworkCommissioningClusterThreadInterfaceScanResult : NSObject
@property (copy) NSData * _Nonnull DiscoveryResponse;
@end

@interface CHIPNetworkCommissioningClusterWiFiInterfaceScanResult : NSObject
@property (copy) NSNumber * _Nonnull Security;
@property (copy) NSData * _Nonnull Ssid;
@property (copy) NSData * _Nonnull Bssid;
@property (copy) NSNumber * _Nonnull Channel;
@property (copy) NSNumber * _Nonnull FrequencyBand;
@end

@interface CHIPGeneralDiagnosticsClusterNetworkInterfaceType : NSObject
@property (copy) NSString * _Nonnull Name;
@property (copy) NSNumber * _Nonnull FabricConnected;
@property (copy) NSNumber * _Nonnull OffPremiseServicesReachableIPv4;
@property (copy) NSNumber * _Nonnull OffPremiseServicesReachableIPv6;
@property (copy) NSData * _Nonnull HardwareAddress;
@property (copy) NSNumber * _Nonnull Type;
@end

@interface CHIPSoftwareDiagnosticsClusterSoftwareFault : NSObject
@property (copy) NSNumber * _Nonnull Id;
@property (copy) NSString * _Nonnull Name;
@property (copy) NSData * _Nonnull FaultRecording;
@end

@interface CHIPSoftwareDiagnosticsClusterThreadMetrics : NSObject
@property (copy) NSNumber * _Nonnull Id;
@property (copy) NSString * _Nonnull Name;
@property (copy) NSNumber * _Nonnull StackFreeCurrent;
@property (copy) NSNumber * _Nonnull StackFreeMinimum;
@property (copy) NSNumber * _Nonnull StackSize;
@end

@interface CHIPThreadNetworkDiagnosticsClusterNeighborTable : NSObject
@property (copy) NSNumber * _Nonnull ExtAddress;
@property (copy) NSNumber * _Nonnull Age;
@property (copy) NSNumber * _Nonnull Rloc16;
@property (copy) NSNumber * _Nonnull LinkFrameCounter;
@property (copy) NSNumber * _Nonnull MleFrameCounter;
@property (copy) NSNumber * _Nonnull Lqi;
@property (copy) NSNumber * _Nonnull AverageRssi;
@property (copy) NSNumber * _Nonnull LastRssi;
@property (copy) NSNumber * _Nonnull FrameErrorRate;
@property (copy) NSNumber * _Nonnull MessageErrorRate;
@property (copy) NSNumber * _Nonnull RxOnWhenIdle;
@property (copy) NSNumber * _Nonnull FullThreadDevice;
@property (copy) NSNumber * _Nonnull FullNetworkData;
@property (copy) NSNumber * _Nonnull IsChild;
@end

@interface CHIPThreadNetworkDiagnosticsClusterOperationalDatasetComponents : NSObject
@property (copy) NSNumber * _Nonnull ActiveTimestampPresent;
@property (copy) NSNumber * _Nonnull PendingTimestampPresent;
@property (copy) NSNumber * _Nonnull MasterKeyPresent;
@property (copy) NSNumber * _Nonnull NetworkNamePresent;
@property (copy) NSNumber * _Nonnull ExtendedPanIdPresent;
@property (copy) NSNumber * _Nonnull MeshLocalPrefixPresent;
@property (copy) NSNumber * _Nonnull DelayPresent;
@property (copy) NSNumber * _Nonnull PanIdPresent;
@property (copy) NSNumber * _Nonnull ChannelPresent;
@property (copy) NSNumber * _Nonnull PskcPresent;
@property (copy) NSNumber * _Nonnull SecurityPolicyPresent;
@property (copy) NSNumber * _Nonnull ChannelMaskPresent;
@end

@interface CHIPThreadNetworkDiagnosticsClusterRouteTable : NSObject
@property (copy) NSNumber * _Nonnull ExtAddress;
@property (copy) NSNumber * _Nonnull Rloc16;
@property (copy) NSNumber * _Nonnull RouterId;
@property (copy) NSNumber * _Nonnull NextHop;
@property (copy) NSNumber * _Nonnull PathCost;
@property (copy) NSNumber * _Nonnull LQIIn;
@property (copy) NSNumber * _Nonnull LQIOut;
@property (copy) NSNumber * _Nonnull Age;
@property (copy) NSNumber * _Nonnull Allocated;
@property (copy) NSNumber * _Nonnull LinkEstablished;
@end

@interface CHIPThreadNetworkDiagnosticsClusterSecurityPolicy : NSObject
@property (copy) NSNumber * _Nonnull RotationTime;
@property (copy) NSNumber * _Nonnull Flags;
@end

@interface CHIPOperationalCredentialsClusterFabricDescriptor : NSObject
@property (copy) NSNumber * _Nonnull FabricIndex;
@property (copy) NSData * _Nonnull RootPublicKey;
@property (copy) NSNumber * _Nonnull VendorId;
@property (copy) NSNumber * _Nonnull FabricId;
@property (copy) NSNumber * _Nonnull NodeId;
@property (copy) NSString * _Nonnull Label;
@end

@interface CHIPOperationalCredentialsClusterNOCStruct : NSObject
@property (copy) NSNumber * _Nonnull FabricIndex;
@property (copy) NSData * _Nonnull Noc;
@end

@interface CHIPFixedLabelClusterLabelStruct : NSObject
@property (copy) NSString * _Nonnull Label;
@property (copy) NSString * _Nonnull Value;
@end

@interface CHIPModeSelectClusterModeOptionStruct : NSObject
@property (copy) NSString * _Nonnull Label;
@property (copy) NSNumber * _Nonnull Mode;
@property (copy) NSNumber * _Nonnull SemanticTag;
@end

@interface CHIPModeSelectClusterSemanticTag : NSObject
@property (copy) NSNumber * _Nonnull MfgCode;
@property (copy) NSNumber * _Nonnull Value;
@end

@interface CHIPIasAceClusterIasAceZoneStatusResult : NSObject
@property (copy) NSNumber * _Nonnull ZoneId;
@property (copy) NSNumber * _Nonnull ZoneStatus;
@end

@interface CHIPTvChannelClusterTvChannelInfo : NSObject
@property (copy) NSNumber * _Nonnull MajorNumber;
@property (copy) NSNumber * _Nonnull MinorNumber;
@property (copy) NSString * _Nonnull Name;
@property (copy) NSString * _Nonnull CallSign;
@property (copy) NSString * _Nonnull AffiliateCallSign;
@end

@interface CHIPTvChannelClusterTvChannelLineupInfo : NSObject
@property (copy) NSString * _Nonnull OperatorName;
@property (copy) NSString * _Nonnull LineupName;
@property (copy) NSString * _Nonnull PostalCode;
@property (copy) NSNumber * _Nonnull LineupInfoType;
@end

@interface CHIPTargetNavigatorClusterNavigateTargetTargetInfo : NSObject
@property (copy) NSNumber * _Nonnull Identifier;
@property (copy) NSString * _Nonnull Name;
@end

@interface CHIPMediaPlaybackClusterMediaPlaybackPosition : NSObject
@property (copy) NSNumber * _Nonnull UpdatedAt;
@property (copy) NSNumber * _Nonnull Position;
@end

@interface CHIPMediaInputClusterMediaInputInfo : NSObject
@property (copy) NSNumber * _Nonnull Index;
@property (copy) NSNumber * _Nonnull InputType;
@property (copy) NSString * _Nonnull Name;
@property (copy) NSString * _Nonnull Description;
@end

@interface CHIPContentLauncherClusterContentLaunchAdditionalInfo : NSObject
@property (copy) NSString * _Nonnull Name;
@property (copy) NSString * _Nonnull Value;
@end

@interface CHIPContentLauncherClusterContentLaunchParamater : NSObject
@property (copy) NSNumber * _Nonnull Type;
@property (copy) NSString * _Nonnull Value;
@property (copy) NSArray * _Nonnull ExternalIDList;
@end

@interface CHIPContentLauncherClusterContentLaunchBrandingInformation : NSObject
@property (copy) NSString * _Nonnull ProviderName;
@property (copy) NSNumber * _Nonnull Background;
@property (copy) NSNumber * _Nonnull Logo;
@property (copy) NSNumber * _Nonnull ProgressBar;
@property (copy) NSNumber * _Nonnull Splash;
@property (copy) NSNumber * _Nonnull WaterMark;
@end

@interface CHIPContentLauncherClusterContentLaunchDimension : NSObject
@property (copy) NSString * _Nonnull Width;
@property (copy) NSString * _Nonnull Height;
@property (copy) NSNumber * _Nonnull Metric;
@end

@interface CHIPContentLauncherClusterContentLaunchStyleInformation : NSObject
@property (copy) NSString * _Nonnull ImageUrl;
@property (copy) NSString * _Nonnull Color;
@property (copy) NSNumber * _Nonnull Size;
@end

@interface CHIPAudioOutputClusterAudioOutputInfo : NSObject
@property (copy) NSNumber * _Nonnull Index;
@property (copy) NSNumber * _Nonnull OutputType;
@property (copy) NSString * _Nonnull Name;
@end

@interface CHIPApplicationLauncherClusterApplicationLauncherApp : NSObject
@property (copy) NSNumber * _Nonnull CatalogVendorId;
@property (copy) NSString * _Nonnull ApplicationId;
@end

@interface CHIPTestClusterClusterSimpleStruct : NSObject
@property (copy) NSNumber * _Nonnull A;
@property (copy) NSNumber * _Nonnull B;
@property (copy) NSNumber * _Nonnull C;
@property (copy) NSData * _Nonnull D;
@property (copy) NSString * _Nonnull E;
@property (copy) NSNumber * _Nonnull F;
@end

@interface CHIPTestClusterClusterNullablesAndOptionalsStruct : NSObject
@property (copy) NSNumber * _Nullable NullableInt;
@property (copy) NSNumber * _Nullable OptionalInt;
@property (copy) NSNumber * _Nullable NullableOptionalInt;
@property (copy) NSString * _Nullable NullableString;
@property (copy) NSString * _Nullable OptionalString;
@property (copy) NSString * _Nullable NullableOptionalString;
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nullable NullableStruct;
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nullable OptionalStruct;
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nullable NullableOptionalStruct;
@property (copy) NSArray * _Nullable NullableList;
@property (copy) NSArray * _Nullable OptionalList;
@property (copy) NSArray * _Nullable NullableOptionalList;
@end

@interface CHIPTestClusterClusterNestedStruct : NSObject
@property (copy) NSNumber * _Nonnull A;
@property (copy) NSNumber * _Nonnull B;
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nonnull C;
@end

@interface CHIPTestClusterClusterNestedStructList : NSObject
@property (copy) NSNumber * _Nonnull A;
@property (copy) NSNumber * _Nonnull B;
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nonnull C;
@property (copy) NSArray * _Nonnull D;
@property (copy) NSArray * _Nonnull E;
@property (copy) NSArray * _Nonnull F;
@property (copy) NSArray * _Nonnull G;
@end

@interface CHIPTestClusterClusterDoubleNestedStructList : NSObject
@property (copy) NSArray * _Nonnull A;
@end

@interface CHIPTestClusterClusterTestListStructOctet : NSObject
@property (copy) NSNumber * _Nonnull FabricIndex;
@property (copy) NSData * _Nonnull OperationalCert;
@end

@interface CHIPGroupKeyManagementClusterGroupKey : NSObject
@property (copy) NSNumber * _Nonnull VendorId;
@property (copy) NSNumber * _Nonnull GroupKeyIndex;
@property (copy) NSData * _Nonnull GroupKeyRoot;
@property (copy) NSNumber * _Nonnull GroupKeyEpochStartTime;
@property (copy) NSNumber * _Nonnull GroupKeySecurityPolicy;
@end

@interface CHIPGroupKeyManagementClusterGroupState : NSObject
@property (copy) NSNumber * _Nonnull VendorId;
@property (copy) NSNumber * _Nonnull VendorGroupId;
@property (copy) NSNumber * _Nonnull GroupKeySetIndex;
@end

#endif /* CHIP_STRUCTS_H */
