/*
 *
 *    Copyright (c) 2021 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#ifndef CHIP_COMMAND_PAYLOADS_H
#define CHIP_COMMAND_PAYLOADS_H

#import <Foundation/Foundation.h>
#import <CHIP/CHIPStructsObjc.h>

@interface CHIPIdentifyClusterIdentifyPayload : NSObject
@property (copy) NSNumber * _Nonnull IdentifyTime;
@end

@interface CHIPIdentifyClusterIdentifyQueryResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Timeout;
@end

@interface CHIPIdentifyClusterIdentifyQueryPayload : NSObject
@end

@interface CHIPIdentifyClusterTriggerEffectPayload : NSObject
@property (copy) NSNumber * _Nonnull EffectIdentifier;
@property (copy) NSNumber * _Nonnull EffectVariant;
@end

@interface CHIPGroupsClusterAddGroupPayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSString * _Nonnull GroupName;
@end

@interface CHIPGroupsClusterAddGroupResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull GroupId;
@end

@interface CHIPGroupsClusterViewGroupPayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@end

@interface CHIPGroupsClusterViewGroupResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSString * _Nonnull GroupName;
@end

@interface CHIPGroupsClusterGetGroupMembershipPayload : NSObject
@property (copy) NSNumber * _Nonnull GroupCount;
@property (copy) NSArray * _Nonnull GroupList;
@end

@interface CHIPGroupsClusterGetGroupMembershipResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Capacity;
@property (copy) NSNumber * _Nonnull GroupCount;
@property (copy) NSArray * _Nonnull GroupList;
@end

@interface CHIPGroupsClusterRemoveGroupPayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@end

@interface CHIPGroupsClusterRemoveGroupResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull GroupId;
@end

@interface CHIPGroupsClusterRemoveAllGroupsPayload : NSObject
@end

@interface CHIPGroupsClusterAddGroupIfIdentifyingPayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSString * _Nonnull GroupName;
@end

@interface CHIPScenesClusterAddScenePayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSString * _Nonnull SceneName;
@property (copy) NSArray * _Nonnull ExtensionFieldSets;
@end

@interface CHIPScenesClusterAddSceneResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@end

@interface CHIPScenesClusterViewScenePayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@end

@interface CHIPScenesClusterViewSceneResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSString * _Nonnull SceneName;
@property (copy) NSArray * _Nonnull ExtensionFieldSets;
@end

@interface CHIPScenesClusterRemoveScenePayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@end

@interface CHIPScenesClusterRemoveSceneResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@end

@interface CHIPScenesClusterRemoveAllScenesPayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@end

@interface CHIPScenesClusterRemoveAllScenesResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull GroupId;
@end

@interface CHIPScenesClusterStoreScenePayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@end

@interface CHIPScenesClusterStoreSceneResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@end

@interface CHIPScenesClusterRecallScenePayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@property (copy) NSNumber * _Nonnull TransitionTime;
@end

@interface CHIPScenesClusterGetSceneMembershipPayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@end

@interface CHIPScenesClusterGetSceneMembershipResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull Capacity;
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneCount;
@property (copy) NSArray * _Nonnull SceneList;
@end

@interface CHIPScenesClusterEnhancedAddScenePayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSString * _Nonnull SceneName;
@property (copy) NSArray * _Nonnull ExtensionFieldSets;
@end

@interface CHIPScenesClusterEnhancedAddSceneResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@end

@interface CHIPScenesClusterEnhancedViewScenePayload : NSObject
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@end

@interface CHIPScenesClusterEnhancedViewSceneResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull SceneId;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSString * _Nonnull SceneName;
@property (copy) NSArray * _Nonnull ExtensionFieldSets;
@end

@interface CHIPScenesClusterCopyScenePayload : NSObject
@property (copy) NSNumber * _Nonnull Mode;
@property (copy) NSNumber * _Nonnull GroupIdFrom;
@property (copy) NSNumber * _Nonnull SceneIdFrom;
@property (copy) NSNumber * _Nonnull GroupIdTo;
@property (copy) NSNumber * _Nonnull SceneIdTo;
@end

@interface CHIPScenesClusterCopySceneResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull GroupIdFrom;
@property (copy) NSNumber * _Nonnull SceneIdFrom;
@end

@interface CHIPOnOffClusterOffPayload : NSObject
@end

@interface CHIPOnOffClusterSampleMfgSpecificOffWithTransitionPayload : NSObject
@end

@interface CHIPOnOffClusterOnPayload : NSObject
@end

@interface CHIPOnOffClusterSampleMfgSpecificOnWithTransitionPayload : NSObject
@end

@interface CHIPOnOffClusterSampleMfgSpecificOnWithTransition2Payload : NSObject
@end

@interface CHIPOnOffClusterTogglePayload : NSObject
@end

@interface CHIPOnOffClusterSampleMfgSpecificToggleWithTransitionPayload : NSObject
@end

@interface CHIPOnOffClusterSampleMfgSpecificToggleWithTransition2Payload : NSObject
@end

@interface CHIPOnOffClusterOffWithEffectPayload : NSObject
@property (copy) NSNumber * _Nonnull EffectId;
@property (copy) NSNumber * _Nonnull EffectVariant;
@end

@interface CHIPOnOffClusterOnWithRecallGlobalScenePayload : NSObject
@end

@interface CHIPOnOffClusterOnWithTimedOffPayload : NSObject
@property (copy) NSNumber * _Nonnull OnOffControl;
@property (copy) NSNumber * _Nonnull OnTime;
@property (copy) NSNumber * _Nonnull OffWaitTime;
@end

@interface CHIPLevelControlClusterMoveToLevelPayload : NSObject
@property (copy) NSNumber * _Nonnull Level;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionMask;
@property (copy) NSNumber * _Nonnull OptionOverride;
@end

@interface CHIPLevelControlClusterMovePayload : NSObject
@property (copy) NSNumber * _Nonnull MoveMode;
@property (copy) NSNumber * _Nonnull Rate;
@property (copy) NSNumber * _Nonnull OptionMask;
@property (copy) NSNumber * _Nonnull OptionOverride;
@end

@interface CHIPLevelControlClusterStepPayload : NSObject
@property (copy) NSNumber * _Nonnull StepMode;
@property (copy) NSNumber * _Nonnull StepSize;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionMask;
@property (copy) NSNumber * _Nonnull OptionOverride;
@end

@interface CHIPLevelControlClusterStopPayload : NSObject
@property (copy) NSNumber * _Nonnull OptionMask;
@property (copy) NSNumber * _Nonnull OptionOverride;
@end

@interface CHIPLevelControlClusterMoveToLevelWithOnOffPayload : NSObject
@property (copy) NSNumber * _Nonnull Level;
@property (copy) NSNumber * _Nonnull TransitionTime;
@end

@interface CHIPLevelControlClusterMoveWithOnOffPayload : NSObject
@property (copy) NSNumber * _Nonnull MoveMode;
@property (copy) NSNumber * _Nonnull Rate;
@end

@interface CHIPLevelControlClusterStepWithOnOffPayload : NSObject
@property (copy) NSNumber * _Nonnull StepMode;
@property (copy) NSNumber * _Nonnull StepSize;
@property (copy) NSNumber * _Nonnull TransitionTime;
@end

@interface CHIPLevelControlClusterStopWithOnOffPayload : NSObject
@end

@interface CHIPAlarmsClusterResetAlarmPayload : NSObject
@property (copy) NSNumber * _Nonnull AlarmCode;
@property (copy) NSNumber * _Nonnull ClusterId;
@end

@interface CHIPAlarmsClusterAlarmPayload : NSObject
@property (copy) NSNumber * _Nonnull AlarmCode;
@property (copy) NSNumber * _Nonnull ClusterId;
@end

@interface CHIPAlarmsClusterResetAllAlarmsPayload : NSObject
@end

@interface CHIPAlarmsClusterGetAlarmResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull AlarmCode;
@property (copy) NSNumber * _Nonnull ClusterId;
@property (copy) NSNumber * _Nonnull TimeStamp;
@end

@interface CHIPAlarmsClusterGetAlarmPayload : NSObject
@end

@interface CHIPAlarmsClusterResetAlarmLogPayload : NSObject
@end

@interface CHIPPowerProfileClusterPowerProfileRequestPayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@end

@interface CHIPPowerProfileClusterPowerProfileNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull TotalProfileNum;
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull NumOfTransferredPhases;
@property (copy) NSArray * _Nonnull TransferredPhases;
@end

@interface CHIPPowerProfileClusterPowerProfileStateRequestPayload : NSObject
@end

@interface CHIPPowerProfileClusterPowerProfileResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull TotalProfileNum;
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull NumOfTransferredPhases;
@property (copy) NSArray * _Nonnull TransferredPhases;
@end

@interface CHIPPowerProfileClusterGetPowerProfilePriceResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull Currency;
@property (copy) NSNumber * _Nonnull Price;
@property (copy) NSNumber * _Nonnull PriceTrailingDigit;
@end

@interface CHIPPowerProfileClusterPowerProfileStateResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileCount;
@property (copy) NSArray * _Nonnull PowerProfileRecords;
@end

@interface CHIPPowerProfileClusterGetOverallSchedulePriceResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Currency;
@property (copy) NSNumber * _Nonnull Price;
@property (copy) NSNumber * _Nonnull PriceTrailingDigit;
@end

@interface CHIPPowerProfileClusterGetPowerProfilePricePayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@end

@interface CHIPPowerProfileClusterEnergyPhasesScheduleNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull NumOfScheduledPhases;
@property (copy) NSArray * _Nonnull ScheduledPhases;
@end

@interface CHIPPowerProfileClusterPowerProfilesStateNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileCount;
@property (copy) NSArray * _Nonnull PowerProfileRecords;
@end

@interface CHIPPowerProfileClusterEnergyPhasesScheduleResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull NumOfScheduledPhases;
@property (copy) NSArray * _Nonnull ScheduledPhases;
@end

@interface CHIPPowerProfileClusterGetOverallSchedulePricePayload : NSObject
@end

@interface CHIPPowerProfileClusterPowerProfileScheduleConstraintsRequestPayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@end

@interface CHIPPowerProfileClusterEnergyPhasesScheduleRequestPayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@end

@interface CHIPPowerProfileClusterEnergyPhasesScheduleStateRequestPayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@end

@interface CHIPPowerProfileClusterEnergyPhasesScheduleStateResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull NumOfScheduledPhases;
@property (copy) NSArray * _Nonnull ScheduledPhases;
@end

@interface CHIPPowerProfileClusterGetPowerProfilePriceExtendedResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull Currency;
@property (copy) NSNumber * _Nonnull Price;
@property (copy) NSNumber * _Nonnull PriceTrailingDigit;
@end

@interface CHIPPowerProfileClusterEnergyPhasesScheduleStateNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull NumOfScheduledPhases;
@property (copy) NSArray * _Nonnull ScheduledPhases;
@end

@interface CHIPPowerProfileClusterPowerProfileScheduleConstraintsNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull StartAfter;
@property (copy) NSNumber * _Nonnull StopBefore;
@end

@interface CHIPPowerProfileClusterPowerProfileScheduleConstraintsResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull StartAfter;
@property (copy) NSNumber * _Nonnull StopBefore;
@end

@interface CHIPPowerProfileClusterGetPowerProfilePriceExtendedPayload : NSObject
@property (copy) NSNumber * _Nonnull Options;
@property (copy) NSNumber * _Nonnull PowerProfileId;
@property (copy) NSNumber * _Nonnull PowerProfileStartTime;
@end

@interface CHIPApplianceControlClusterExecutionOfACommandPayload : NSObject
@property (copy) NSNumber * _Nonnull CommandId;
@end

@interface CHIPApplianceControlClusterSignalStateResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ApplianceStatus;
@property (copy) NSNumber * _Nonnull RemoteEnableFlagsAndDeviceStatus2;
@property (copy) NSNumber * _Nonnull ApplianceStatus2;
@end

@interface CHIPApplianceControlClusterSignalStatePayload : NSObject
@end

@interface CHIPApplianceControlClusterSignalStateNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull ApplianceStatus;
@property (copy) NSNumber * _Nonnull RemoteEnableFlagsAndDeviceStatus2;
@property (copy) NSNumber * _Nonnull ApplianceStatus2;
@end

@interface CHIPApplianceControlClusterWriteFunctionsPayload : NSObject
@property (copy) NSNumber * _Nonnull FunctionId;
@property (copy) NSNumber * _Nonnull FunctionDataType;
@property (copy) NSArray * _Nonnull FunctionData;
@end

@interface CHIPApplianceControlClusterOverloadPauseResumePayload : NSObject
@end

@interface CHIPApplianceControlClusterOverloadPausePayload : NSObject
@end

@interface CHIPApplianceControlClusterOverloadWarningPayload : NSObject
@property (copy) NSNumber * _Nonnull WarningEvent;
@end

@interface CHIPPollControlClusterCheckInPayload : NSObject
@end

@interface CHIPPollControlClusterCheckInResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull StartFastPolling;
@property (copy) NSNumber * _Nonnull FastPollTimeout;
@end

@interface CHIPPollControlClusterFastPollStopPayload : NSObject
@end

@interface CHIPPollControlClusterSetLongPollIntervalPayload : NSObject
@property (copy) NSNumber * _Nonnull NewLongPollInterval;
@end

@interface CHIPPollControlClusterSetShortPollIntervalPayload : NSObject
@property (copy) NSNumber * _Nonnull NewShortPollInterval;
@end

@interface CHIPBridgedActionsClusterInstantActionPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@end

@interface CHIPBridgedActionsClusterInstantActionWithTransitionPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@property (copy) NSNumber * _Nonnull TransitionTime;
@end

@interface CHIPBridgedActionsClusterStartActionPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@end

@interface CHIPBridgedActionsClusterStartActionWithDurationPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@property (copy) NSNumber * _Nonnull Duration;
@end

@interface CHIPBridgedActionsClusterStopActionPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@end

@interface CHIPBridgedActionsClusterPauseActionPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@end

@interface CHIPBridgedActionsClusterPauseActionWithDurationPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@property (copy) NSNumber * _Nonnull Duration;
@end

@interface CHIPBridgedActionsClusterResumeActionPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@end

@interface CHIPBridgedActionsClusterEnableActionPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@end

@interface CHIPBridgedActionsClusterEnableActionWithDurationPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@property (copy) NSNumber * _Nonnull Duration;
@end

@interface CHIPBridgedActionsClusterDisableActionPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@end

@interface CHIPBridgedActionsClusterDisableActionWithDurationPayload : NSObject
@property (copy) NSNumber * _Nonnull ActionID;
@property (copy) NSNumber * _Nullable InvokeID;
@property (copy) NSNumber * _Nonnull Duration;
@end

@interface CHIPBasicClusterStartUpPayload : NSObject
@end

@interface CHIPBasicClusterMfgSpecificPingPayload : NSObject
@end

@interface CHIPBasicClusterShutDownPayload : NSObject
@end

@interface CHIPBasicClusterLeavePayload : NSObject
@end

@interface CHIPOtaSoftwareUpdateProviderClusterQueryImagePayload : NSObject
@property (copy) NSNumber * _Nonnull VendorId;
@property (copy) NSNumber * _Nonnull ProductId;
@property (copy) NSNumber * _Nonnull SoftwareVersion;
@property (copy) NSArray * _Nonnull ProtocolsSupported;
@property (copy) NSNumber * _Nullable HardwareVersion;
@property (copy) NSString * _Nullable Location;
@property (copy) NSNumber * _Nullable RequestorCanConsent;
@property (copy) NSData * _Nullable MetadataForProvider;
@end

@interface CHIPOtaSoftwareUpdateProviderClusterApplyUpdateRequestPayload : NSObject
@property (copy) NSData * _Nonnull UpdateToken;
@property (copy) NSNumber * _Nonnull NewVersion;
@end

@interface CHIPOtaSoftwareUpdateProviderClusterNotifyUpdateAppliedPayload : NSObject
@property (copy) NSData * _Nonnull UpdateToken;
@property (copy) NSNumber * _Nonnull SoftwareVersion;
@end

@interface CHIPOtaSoftwareUpdateProviderClusterQueryImageResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nullable DelayedActionTime;
@property (copy) NSString * _Nullable ImageURI;
@property (copy) NSNumber * _Nullable SoftwareVersion;
@property (copy) NSString * _Nullable SoftwareVersionString;
@property (copy) NSData * _Nullable UpdateToken;
@property (copy) NSNumber * _Nullable UserConsentNeeded;
@property (copy) NSData * _Nullable MetadataForRequestor;
@end

@interface CHIPOtaSoftwareUpdateProviderClusterApplyUpdateResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Action;
@property (copy) NSNumber * _Nonnull DelayedActionTime;
@end

@interface CHIPOtaSoftwareUpdateRequestorClusterAnnounceOtaProviderPayload : NSObject
@property (copy) NSNumber * _Nonnull ProviderLocation;
@property (copy) NSNumber * _Nonnull VendorId;
@property (copy) NSNumber * _Nonnull AnnouncementReason;
@property (copy) NSData * _Nullable MetadataForNode;
@end

@interface CHIPGeneralCommissioningClusterArmFailSafePayload : NSObject
@property (copy) NSNumber * _Nonnull ExpiryLengthSeconds;
@property (copy) NSNumber * _Nonnull Breadcrumb;
@property (copy) NSNumber * _Nonnull TimeoutMs;
@end

@interface CHIPGeneralCommissioningClusterArmFailSafeResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ErrorCode;
@property (copy) NSString * _Nonnull DebugText;
@end

@interface CHIPGeneralCommissioningClusterSetRegulatoryConfigPayload : NSObject
@property (copy) NSNumber * _Nonnull Location;
@property (copy) NSString * _Nonnull CountryCode;
@property (copy) NSNumber * _Nonnull Breadcrumb;
@property (copy) NSNumber * _Nonnull TimeoutMs;
@end

@interface CHIPGeneralCommissioningClusterSetRegulatoryConfigResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ErrorCode;
@property (copy) NSString * _Nonnull DebugText;
@end

@interface CHIPGeneralCommissioningClusterCommissioningCompletePayload : NSObject
@end

@interface CHIPGeneralCommissioningClusterCommissioningCompleteResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ErrorCode;
@property (copy) NSString * _Nonnull DebugText;
@end

@interface CHIPNetworkCommissioningClusterScanNetworksPayload : NSObject
@property (copy) NSData * _Nonnull Ssid;
@property (copy) NSNumber * _Nonnull Breadcrumb;
@property (copy) NSNumber * _Nonnull TimeoutMs;
@end

@interface CHIPNetworkCommissioningClusterScanNetworksResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ErrorCode;
@property (copy) NSString * _Nonnull DebugText;
@property (copy) NSArray * _Nonnull WifiScanResults;
@property (copy) NSArray * _Nonnull ThreadScanResults;
@end

@interface CHIPNetworkCommissioningClusterAddWiFiNetworkPayload : NSObject
@property (copy) NSData * _Nonnull Ssid;
@property (copy) NSData * _Nonnull Credentials;
@property (copy) NSNumber * _Nonnull Breadcrumb;
@property (copy) NSNumber * _Nonnull TimeoutMs;
@end

@interface CHIPNetworkCommissioningClusterAddWiFiNetworkResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ErrorCode;
@property (copy) NSString * _Nonnull DebugText;
@end

@interface CHIPNetworkCommissioningClusterUpdateWiFiNetworkPayload : NSObject
@property (copy) NSData * _Nonnull Ssid;
@property (copy) NSData * _Nonnull Credentials;
@property (copy) NSNumber * _Nonnull Breadcrumb;
@property (copy) NSNumber * _Nonnull TimeoutMs;
@end

@interface CHIPNetworkCommissioningClusterUpdateWiFiNetworkResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ErrorCode;
@property (copy) NSString * _Nonnull DebugText;
@end

@interface CHIPNetworkCommissioningClusterAddThreadNetworkPayload : NSObject
@property (copy) NSData * _Nonnull OperationalDataset;
@property (copy) NSNumber * _Nonnull Breadcrumb;
@property (copy) NSNumber * _Nonnull TimeoutMs;
@end

@interface CHIPNetworkCommissioningClusterAddThreadNetworkResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ErrorCode;
@property (copy) NSString * _Nonnull DebugText;
@end

@interface CHIPNetworkCommissioningClusterUpdateThreadNetworkPayload : NSObject
@property (copy) NSData * _Nonnull OperationalDataset;
@property (copy) NSNumber * _Nonnull Breadcrumb;
@property (copy) NSNumber * _Nonnull TimeoutMs;
@end

@interface CHIPNetworkCommissioningClusterUpdateThreadNetworkResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ErrorCode;
@property (copy) NSString * _Nonnull DebugText;
@end

@interface CHIPNetworkCommissioningClusterRemoveNetworkPayload : NSObject
@property (copy) NSData * _Nonnull NetworkID;
@property (copy) NSNumber * _Nonnull Breadcrumb;
@property (copy) NSNumber * _Nonnull TimeoutMs;
@end

@interface CHIPNetworkCommissioningClusterRemoveNetworkResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ErrorCode;
@property (copy) NSString * _Nonnull DebugText;
@end

@interface CHIPNetworkCommissioningClusterEnableNetworkPayload : NSObject
@property (copy) NSData * _Nonnull NetworkID;
@property (copy) NSNumber * _Nonnull Breadcrumb;
@property (copy) NSNumber * _Nonnull TimeoutMs;
@end

@interface CHIPNetworkCommissioningClusterEnableNetworkResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ErrorCode;
@property (copy) NSString * _Nonnull DebugText;
@end

@interface CHIPNetworkCommissioningClusterDisableNetworkPayload : NSObject
@property (copy) NSData * _Nonnull NetworkID;
@property (copy) NSNumber * _Nonnull Breadcrumb;
@property (copy) NSNumber * _Nonnull TimeoutMs;
@end

@interface CHIPNetworkCommissioningClusterDisableNetworkResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ErrorCode;
@property (copy) NSString * _Nonnull DebugText;
@end

@interface CHIPDiagnosticLogsClusterRetrieveLogsRequestPayload : NSObject
@property (copy) NSNumber * _Nonnull Intent;
@property (copy) NSNumber * _Nonnull RequestedProtocol;
@property (copy) NSData * _Nonnull TransferFileDesignator;
@end

@interface CHIPDiagnosticLogsClusterRetrieveLogsResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSData * _Nonnull Content;
@property (copy) NSNumber * _Nonnull TimeStamp;
@property (copy) NSNumber * _Nonnull TimeSinceBoot;
@end

@interface CHIPSoftwareDiagnosticsClusterResetWatermarksPayload : NSObject
@end

@interface CHIPThreadNetworkDiagnosticsClusterResetCountsPayload : NSObject
@end

@interface CHIPWiFiNetworkDiagnosticsClusterResetCountsPayload : NSObject
@end

@interface CHIPEthernetNetworkDiagnosticsClusterResetCountsPayload : NSObject
@end

@interface CHIPBridgedDeviceBasicClusterStartUpPayload : NSObject
@end

@interface CHIPBridgedDeviceBasicClusterShutDownPayload : NSObject
@end

@interface CHIPBridgedDeviceBasicClusterLeavePayload : NSObject
@end

@interface CHIPBridgedDeviceBasicClusterReachableChangedPayload : NSObject
@end

@interface CHIPAdministratorCommissioningClusterOpenCommissioningWindowPayload : NSObject
@property (copy) NSNumber * _Nonnull CommissioningTimeout;
@property (copy) NSData * _Nonnull PAKEVerifier;
@property (copy) NSNumber * _Nonnull Discriminator;
@property (copy) NSNumber * _Nonnull Iterations;
@property (copy) NSData * _Nonnull Salt;
@property (copy) NSNumber * _Nonnull PasscodeID;
@end

@interface CHIPAdministratorCommissioningClusterOpenBasicCommissioningWindowPayload : NSObject
@property (copy) NSNumber * _Nonnull CommissioningTimeout;
@end

@interface CHIPAdministratorCommissioningClusterRevokeCommissioningPayload : NSObject
@end

@interface CHIPOperationalCredentialsClusterAttestationRequestPayload : NSObject
@property (copy) NSData * _Nonnull AttestationNonce;
@end

@interface CHIPOperationalCredentialsClusterAttestationResponsePayload : NSObject
@property (copy) NSData * _Nonnull AttestationElements;
@property (copy) NSData * _Nonnull Signature;
@end

@interface CHIPOperationalCredentialsClusterCertificateChainRequestPayload : NSObject
@property (copy) NSNumber * _Nonnull CertificateType;
@end

@interface CHIPOperationalCredentialsClusterCertificateChainResponsePayload : NSObject
@property (copy) NSData * _Nonnull Certificate;
@end

@interface CHIPOperationalCredentialsClusterOpCSRRequestPayload : NSObject
@property (copy) NSData * _Nonnull CSRNonce;
@end

@interface CHIPOperationalCredentialsClusterOpCSRResponsePayload : NSObject
@property (copy) NSData * _Nonnull NOCSRElements;
@property (copy) NSData * _Nonnull AttestationSignature;
@end

@interface CHIPOperationalCredentialsClusterAddNOCPayload : NSObject
@property (copy) NSData * _Nonnull NOCValue;
@property (copy) NSData * _Nullable ICACValue;
@property (copy) NSData * _Nonnull IPKValue;
@property (copy) NSNumber * _Nonnull CaseAdminNode;
@property (copy) NSNumber * _Nonnull AdminVendorId;
@end

@interface CHIPOperationalCredentialsClusterUpdateNOCPayload : NSObject
@property (copy) NSData * _Nonnull NOCValue;
@property (copy) NSData * _Nullable ICACValue;
@end

@interface CHIPOperationalCredentialsClusterNOCResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull StatusCode;
@property (copy) NSNumber * _Nonnull FabricIndex;
@property (copy) NSString * _Nonnull DebugText;
@end

@interface CHIPOperationalCredentialsClusterUpdateFabricLabelPayload : NSObject
@property (copy) NSString * _Nonnull Label;
@end

@interface CHIPOperationalCredentialsClusterRemoveFabricPayload : NSObject
@property (copy) NSNumber * _Nonnull FabricIndex;
@end

@interface CHIPOperationalCredentialsClusterAddTrustedRootCertificatePayload : NSObject
@property (copy) NSData * _Nonnull RootCertificate;
@end

@interface CHIPOperationalCredentialsClusterRemoveTrustedRootCertificatePayload : NSObject
@property (copy) NSData * _Nonnull TrustedRootIdentifier;
@end

@interface CHIPModeSelectClusterChangeToModePayload : NSObject
@property (copy) NSNumber * _Nonnull NewMode;
@end

@interface CHIPDoorLockClusterLockDoorPayload : NSObject
@property (copy) NSData * _Nonnull Pin;
@end

@interface CHIPDoorLockClusterLockDoorResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterUnlockDoorPayload : NSObject
@property (copy) NSData * _Nonnull Pin;
@end

@interface CHIPDoorLockClusterUnlockDoorResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterTogglePayload : NSObject
@property (copy) NSString * _Nonnull Pin;
@end

@interface CHIPDoorLockClusterToggleResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterUnlockWithTimeoutPayload : NSObject
@property (copy) NSNumber * _Nonnull TimeoutInSeconds;
@property (copy) NSData * _Nonnull Pin;
@end

@interface CHIPDoorLockClusterUnlockWithTimeoutResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterGetLogRecordPayload : NSObject
@property (copy) NSNumber * _Nonnull LogIndex;
@end

@interface CHIPDoorLockClusterGetLogRecordResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull LogEntryId;
@property (copy) NSNumber * _Nonnull Timestamp;
@property (copy) NSNumber * _Nonnull EventType;
@property (copy) NSNumber * _Nonnull Source;
@property (copy) NSNumber * _Nonnull EventIdOrAlarmCode;
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSData * _Nonnull Pin;
@end

@interface CHIPDoorLockClusterSetPinPayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull UserStatus;
@property (copy) NSNumber * _Nonnull UserType;
@property (copy) NSData * _Nonnull Pin;
@end

@interface CHIPDoorLockClusterSetPinResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterGetPinPayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@end

@interface CHIPDoorLockClusterGetPinResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull UserStatus;
@property (copy) NSNumber * _Nonnull UserType;
@property (copy) NSData * _Nonnull Pin;
@end

@interface CHIPDoorLockClusterClearPinPayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@end

@interface CHIPDoorLockClusterClearPinResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterClearAllPinsPayload : NSObject
@end

@interface CHIPDoorLockClusterClearAllPinsResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterSetUserStatusPayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull UserStatus;
@end

@interface CHIPDoorLockClusterSetUserStatusResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterGetUserStatusPayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@end

@interface CHIPDoorLockClusterGetUserStatusResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterSetWeekdaySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull DaysMask;
@property (copy) NSNumber * _Nonnull StartHour;
@property (copy) NSNumber * _Nonnull StartMinute;
@property (copy) NSNumber * _Nonnull EndHour;
@property (copy) NSNumber * _Nonnull EndMinute;
@end

@interface CHIPDoorLockClusterSetWeekdayScheduleResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterGetWeekdaySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@property (copy) NSNumber * _Nonnull UserId;
@end

@interface CHIPDoorLockClusterGetWeekdayScheduleResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull DaysMask;
@property (copy) NSNumber * _Nonnull StartHour;
@property (copy) NSNumber * _Nonnull StartMinute;
@property (copy) NSNumber * _Nonnull EndHour;
@property (copy) NSNumber * _Nonnull EndMinute;
@end

@interface CHIPDoorLockClusterClearWeekdaySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@property (copy) NSNumber * _Nonnull UserId;
@end

@interface CHIPDoorLockClusterClearWeekdayScheduleResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterSetYeardaySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull LocalStartTime;
@property (copy) NSNumber * _Nonnull LocalEndTime;
@end

@interface CHIPDoorLockClusterSetYeardayScheduleResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterGetYeardaySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@property (copy) NSNumber * _Nonnull UserId;
@end

@interface CHIPDoorLockClusterGetYeardayScheduleResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull LocalStartTime;
@property (copy) NSNumber * _Nonnull LocalEndTime;
@end

@interface CHIPDoorLockClusterClearYeardaySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@property (copy) NSNumber * _Nonnull UserId;
@end

@interface CHIPDoorLockClusterClearYeardayScheduleResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterSetHolidaySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@property (copy) NSNumber * _Nonnull LocalStartTime;
@property (copy) NSNumber * _Nonnull LocalEndTime;
@property (copy) NSNumber * _Nonnull OperatingModeDuringHoliday;
@end

@interface CHIPDoorLockClusterSetHolidayScheduleResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterGetHolidaySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@end

@interface CHIPDoorLockClusterGetHolidayScheduleResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull LocalStartTime;
@property (copy) NSNumber * _Nonnull LocalEndTime;
@property (copy) NSNumber * _Nonnull OperatingModeDuringHoliday;
@end

@interface CHIPDoorLockClusterClearHolidaySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull ScheduleId;
@end

@interface CHIPDoorLockClusterClearHolidayScheduleResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterSetUserTypePayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull UserType;
@end

@interface CHIPDoorLockClusterSetUserTypeResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterGetUserTypePayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@end

@interface CHIPDoorLockClusterGetUserTypeResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull UserType;
@end

@interface CHIPDoorLockClusterSetRfidPayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull UserStatus;
@property (copy) NSNumber * _Nonnull UserType;
@property (copy) NSData * _Nonnull Id;
@end

@interface CHIPDoorLockClusterSetRfidResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterGetRfidPayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@end

@interface CHIPDoorLockClusterGetRfidResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSNumber * _Nonnull UserStatus;
@property (copy) NSNumber * _Nonnull UserType;
@property (copy) NSData * _Nonnull Rfid;
@end

@interface CHIPDoorLockClusterClearRfidPayload : NSObject
@property (copy) NSNumber * _Nonnull UserId;
@end

@interface CHIPDoorLockClusterClearRfidResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterClearAllRfidsPayload : NSObject
@end

@interface CHIPDoorLockClusterClearAllRfidsResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPDoorLockClusterOperationEventNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull Source;
@property (copy) NSNumber * _Nonnull EventCode;
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSData * _Nonnull Pin;
@property (copy) NSNumber * _Nonnull TimeStamp;
@property (copy) NSString * _Nonnull Data;
@end

@interface CHIPDoorLockClusterProgrammingEventNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull Source;
@property (copy) NSNumber * _Nonnull EventCode;
@property (copy) NSNumber * _Nonnull UserId;
@property (copy) NSData * _Nonnull Pin;
@property (copy) NSNumber * _Nonnull UserType;
@property (copy) NSNumber * _Nonnull UserStatus;
@property (copy) NSNumber * _Nonnull TimeStamp;
@property (copy) NSString * _Nonnull Data;
@end

@interface CHIPWindowCoveringClusterUpOrOpenPayload : NSObject
@end

@interface CHIPWindowCoveringClusterDownOrClosePayload : NSObject
@end

@interface CHIPWindowCoveringClusterStopMotionPayload : NSObject
@end

@interface CHIPWindowCoveringClusterGoToLiftValuePayload : NSObject
@property (copy) NSNumber * _Nonnull LiftValue;
@end

@interface CHIPWindowCoveringClusterGoToLiftPercentagePayload : NSObject
@property (copy) NSNumber * _Nonnull LiftPercentageValue;
@property (copy) NSNumber * _Nonnull LiftPercent100thsValue;
@end

@interface CHIPWindowCoveringClusterGoToTiltValuePayload : NSObject
@property (copy) NSNumber * _Nonnull TiltValue;
@end

@interface CHIPWindowCoveringClusterGoToTiltPercentagePayload : NSObject
@property (copy) NSNumber * _Nonnull TiltPercentageValue;
@property (copy) NSNumber * _Nonnull TiltPercent100thsValue;
@end

@interface CHIPBarrierControlClusterBarrierControlGoToPercentPayload : NSObject
@property (copy) NSNumber * _Nonnull PercentOpen;
@end

@interface CHIPBarrierControlClusterBarrierControlStopPayload : NSObject
@end

@interface CHIPThermostatClusterSetpointRaiseLowerPayload : NSObject
@property (copy) NSNumber * _Nonnull Mode;
@property (copy) NSNumber * _Nonnull Amount;
@end

@interface CHIPThermostatClusterCurrentWeeklySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull NumberOfTransitionsForSequence;
@property (copy) NSNumber * _Nonnull DayOfWeekForSequence;
@property (copy) NSNumber * _Nonnull ModeForSequence;
@property (copy) NSArray * _Nonnull Payload;
@end

@interface CHIPThermostatClusterSetWeeklySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull NumberOfTransitionsForSequence;
@property (copy) NSNumber * _Nonnull DayOfWeekForSequence;
@property (copy) NSNumber * _Nonnull ModeForSequence;
@property (copy) NSArray * _Nonnull Payload;
@end

@interface CHIPThermostatClusterRelayStatusLogPayload : NSObject
@property (copy) NSNumber * _Nonnull TimeOfDay;
@property (copy) NSNumber * _Nonnull RelayStatus;
@property (copy) NSNumber * _Nonnull LocalTemperature;
@property (copy) NSNumber * _Nonnull HumidityInPercentage;
@property (copy) NSNumber * _Nonnull Setpoint;
@property (copy) NSNumber * _Nonnull UnreadEntries;
@end

@interface CHIPThermostatClusterGetWeeklySchedulePayload : NSObject
@property (copy) NSNumber * _Nonnull DaysToReturn;
@property (copy) NSNumber * _Nonnull ModeToReturn;
@end

@interface CHIPThermostatClusterClearWeeklySchedulePayload : NSObject
@end

@interface CHIPThermostatClusterGetRelayStatusLogPayload : NSObject
@end

@interface CHIPColorControlClusterMoveToHuePayload : NSObject
@property (copy) NSNumber * _Nonnull Hue;
@property (copy) NSNumber * _Nonnull Direction;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterMoveHuePayload : NSObject
@property (copy) NSNumber * _Nonnull MoveMode;
@property (copy) NSNumber * _Nonnull Rate;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterStepHuePayload : NSObject
@property (copy) NSNumber * _Nonnull StepMode;
@property (copy) NSNumber * _Nonnull StepSize;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterMoveToSaturationPayload : NSObject
@property (copy) NSNumber * _Nonnull Saturation;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterMoveSaturationPayload : NSObject
@property (copy) NSNumber * _Nonnull MoveMode;
@property (copy) NSNumber * _Nonnull Rate;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterStepSaturationPayload : NSObject
@property (copy) NSNumber * _Nonnull StepMode;
@property (copy) NSNumber * _Nonnull StepSize;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterMoveToHueAndSaturationPayload : NSObject
@property (copy) NSNumber * _Nonnull Hue;
@property (copy) NSNumber * _Nonnull Saturation;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterMoveToColorPayload : NSObject
@property (copy) NSNumber * _Nonnull ColorX;
@property (copy) NSNumber * _Nonnull ColorY;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterMoveColorPayload : NSObject
@property (copy) NSNumber * _Nonnull RateX;
@property (copy) NSNumber * _Nonnull RateY;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterStepColorPayload : NSObject
@property (copy) NSNumber * _Nonnull StepX;
@property (copy) NSNumber * _Nonnull StepY;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterMoveToColorTemperaturePayload : NSObject
@property (copy) NSNumber * _Nonnull ColorTemperature;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterEnhancedMoveToHuePayload : NSObject
@property (copy) NSNumber * _Nonnull EnhancedHue;
@property (copy) NSNumber * _Nonnull Direction;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterEnhancedMoveHuePayload : NSObject
@property (copy) NSNumber * _Nonnull MoveMode;
@property (copy) NSNumber * _Nonnull Rate;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterEnhancedStepHuePayload : NSObject
@property (copy) NSNumber * _Nonnull StepMode;
@property (copy) NSNumber * _Nonnull StepSize;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterEnhancedMoveToHueAndSaturationPayload : NSObject
@property (copy) NSNumber * _Nonnull EnhancedHue;
@property (copy) NSNumber * _Nonnull Saturation;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterColorLoopSetPayload : NSObject
@property (copy) NSNumber * _Nonnull UpdateFlags;
@property (copy) NSNumber * _Nonnull Action;
@property (copy) NSNumber * _Nonnull Direction;
@property (copy) NSNumber * _Nonnull Time;
@property (copy) NSNumber * _Nonnull StartHue;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterStopMoveStepPayload : NSObject
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterMoveColorTemperaturePayload : NSObject
@property (copy) NSNumber * _Nonnull MoveMode;
@property (copy) NSNumber * _Nonnull Rate;
@property (copy) NSNumber * _Nonnull ColorTemperatureMinimum;
@property (copy) NSNumber * _Nonnull ColorTemperatureMaximum;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPColorControlClusterStepColorTemperaturePayload : NSObject
@property (copy) NSNumber * _Nonnull StepMode;
@property (copy) NSNumber * _Nonnull StepSize;
@property (copy) NSNumber * _Nonnull TransitionTime;
@property (copy) NSNumber * _Nonnull ColorTemperatureMinimum;
@property (copy) NSNumber * _Nonnull ColorTemperatureMaximum;
@property (copy) NSNumber * _Nonnull OptionsMask;
@property (copy) NSNumber * _Nonnull OptionsOverride;
@end

@interface CHIPIasZoneClusterZoneEnrollResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull EnrollResponseCode;
@property (copy) NSNumber * _Nonnull ZoneId;
@end

@interface CHIPIasZoneClusterZoneStatusChangeNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull ZoneStatus;
@property (copy) NSNumber * _Nonnull ExtendedStatus;
@property (copy) NSNumber * _Nonnull ZoneId;
@property (copy) NSNumber * _Nonnull Delay;
@end

@interface CHIPIasZoneClusterInitiateNormalOperationModePayload : NSObject
@end

@interface CHIPIasZoneClusterZoneEnrollRequestPayload : NSObject
@property (copy) NSNumber * _Nonnull ZoneType;
@property (copy) NSNumber * _Nonnull ManufacturerCode;
@end

@interface CHIPIasZoneClusterInitiateTestModePayload : NSObject
@property (copy) NSNumber * _Nonnull TestModeDuration;
@property (copy) NSNumber * _Nonnull CurrentZoneSensitivityLevel;
@end

@interface CHIPIasZoneClusterInitiateNormalOperationModeResponsePayload : NSObject
@end

@interface CHIPIasZoneClusterInitiateTestModeResponsePayload : NSObject
@end

@interface CHIPIasAceClusterArmPayload : NSObject
@property (copy) NSNumber * _Nonnull ArmMode;
@property (copy) NSString * _Nonnull ArmDisarmCode;
@property (copy) NSNumber * _Nonnull ZoneId;
@end

@interface CHIPIasAceClusterArmResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ArmNotification;
@end

@interface CHIPIasAceClusterBypassPayload : NSObject
@property (copy) NSNumber * _Nonnull NumberOfZones;
@property (copy) NSArray * _Nonnull ZoneIds;
@property (copy) NSString * _Nonnull ArmDisarmCode;
@end

@interface CHIPIasAceClusterGetZoneIdMapResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Section0;
@property (copy) NSNumber * _Nonnull Section1;
@property (copy) NSNumber * _Nonnull Section2;
@property (copy) NSNumber * _Nonnull Section3;
@property (copy) NSNumber * _Nonnull Section4;
@property (copy) NSNumber * _Nonnull Section5;
@property (copy) NSNumber * _Nonnull Section6;
@property (copy) NSNumber * _Nonnull Section7;
@property (copy) NSNumber * _Nonnull Section8;
@property (copy) NSNumber * _Nonnull Section9;
@property (copy) NSNumber * _Nonnull Section10;
@property (copy) NSNumber * _Nonnull Section11;
@property (copy) NSNumber * _Nonnull Section12;
@property (copy) NSNumber * _Nonnull Section13;
@property (copy) NSNumber * _Nonnull Section14;
@property (copy) NSNumber * _Nonnull Section15;
@end

@interface CHIPIasAceClusterEmergencyPayload : NSObject
@end

@interface CHIPIasAceClusterGetZoneInformationResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ZoneId;
@property (copy) NSNumber * _Nonnull ZoneType;
@property (copy) NSNumber * _Nonnull IeeeAddress;
@property (copy) NSString * _Nonnull ZoneLabel;
@end

@interface CHIPIasAceClusterFirePayload : NSObject
@end

@interface CHIPIasAceClusterZoneStatusChangedPayload : NSObject
@property (copy) NSNumber * _Nonnull ZoneId;
@property (copy) NSNumber * _Nonnull ZoneStatus;
@property (copy) NSNumber * _Nonnull AudibleNotification;
@property (copy) NSString * _Nonnull ZoneLabel;
@end

@interface CHIPIasAceClusterPanicPayload : NSObject
@end

@interface CHIPIasAceClusterPanelStatusChangedPayload : NSObject
@property (copy) NSNumber * _Nonnull PanelStatus;
@property (copy) NSNumber * _Nonnull SecondsRemaining;
@property (copy) NSNumber * _Nonnull AudibleNotification;
@property (copy) NSNumber * _Nonnull AlarmStatus;
@end

@interface CHIPIasAceClusterGetZoneIdMapPayload : NSObject
@end

@interface CHIPIasAceClusterGetPanelStatusResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull PanelStatus;
@property (copy) NSNumber * _Nonnull SecondsRemaining;
@property (copy) NSNumber * _Nonnull AudibleNotification;
@property (copy) NSNumber * _Nonnull AlarmStatus;
@end

@interface CHIPIasAceClusterGetZoneInformationPayload : NSObject
@property (copy) NSNumber * _Nonnull ZoneId;
@end

@interface CHIPIasAceClusterSetBypassedZoneListPayload : NSObject
@property (copy) NSNumber * _Nonnull NumberOfZones;
@property (copy) NSArray * _Nonnull ZoneIds;
@end

@interface CHIPIasAceClusterGetPanelStatusPayload : NSObject
@end

@interface CHIPIasAceClusterBypassResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull NumberOfZones;
@property (copy) NSArray * _Nonnull BypassResult;
@end

@interface CHIPIasAceClusterGetBypassedZoneListPayload : NSObject
@end

@interface CHIPIasAceClusterGetZoneStatusResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ZoneStatusComplete;
@property (copy) NSNumber * _Nonnull NumberOfZones;
@property (copy) NSArray * _Nonnull ZoneStatusResult;
@end

@interface CHIPIasAceClusterGetZoneStatusPayload : NSObject
@property (copy) NSNumber * _Nonnull StartingZoneId;
@property (copy) NSNumber * _Nonnull MaxNumberOfZoneIds;
@property (copy) NSNumber * _Nonnull ZoneStatusMaskFlag;
@property (copy) NSNumber * _Nonnull ZoneStatusMask;
@end

@interface CHIPIasWdClusterStartWarningPayload : NSObject
@property (copy) NSNumber * _Nonnull WarningInfo;
@property (copy) NSNumber * _Nonnull WarningDuration;
@property (copy) NSNumber * _Nonnull StrobeDutyCycle;
@property (copy) NSNumber * _Nonnull StrobeLevel;
@end

@interface CHIPIasWdClusterSquawkPayload : NSObject
@property (copy) NSNumber * _Nonnull SquawkInfo;
@end

@interface CHIPTvChannelClusterChangeChannelPayload : NSObject
@property (copy) NSString * _Nonnull Match;
@end

@interface CHIPTvChannelClusterChangeChannelResponsePayload : NSObject
@property (copy) NSArray * _Nonnull ChannelMatch;
@property (copy) NSNumber * _Nonnull ErrorType;
@end

@interface CHIPTvChannelClusterChangeChannelByNumberPayload : NSObject
@property (copy) NSNumber * _Nonnull MajorNumber;
@property (copy) NSNumber * _Nonnull MinorNumber;
@end

@interface CHIPTvChannelClusterSkipChannelPayload : NSObject
@property (copy) NSNumber * _Nonnull Count;
@end

@interface CHIPTargetNavigatorClusterNavigateTargetPayload : NSObject
@property (copy) NSNumber * _Nonnull Target;
@property (copy) NSString * _Nonnull Data;
@end

@interface CHIPTargetNavigatorClusterNavigateTargetResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSString * _Nonnull Data;
@end

@interface CHIPMediaPlaybackClusterMediaPlayPayload : NSObject
@end

@interface CHIPMediaPlaybackClusterMediaPlayResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull MediaPlaybackStatus;
@end

@interface CHIPMediaPlaybackClusterMediaPausePayload : NSObject
@end

@interface CHIPMediaPlaybackClusterMediaPauseResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull MediaPlaybackStatus;
@end

@interface CHIPMediaPlaybackClusterMediaStopPayload : NSObject
@end

@interface CHIPMediaPlaybackClusterMediaStopResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull MediaPlaybackStatus;
@end

@interface CHIPMediaPlaybackClusterMediaStartOverPayload : NSObject
@end

@interface CHIPMediaPlaybackClusterMediaStartOverResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull MediaPlaybackStatus;
@end

@interface CHIPMediaPlaybackClusterMediaPreviousPayload : NSObject
@end

@interface CHIPMediaPlaybackClusterMediaPreviousResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull MediaPlaybackStatus;
@end

@interface CHIPMediaPlaybackClusterMediaNextPayload : NSObject
@end

@interface CHIPMediaPlaybackClusterMediaNextResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull MediaPlaybackStatus;
@end

@interface CHIPMediaPlaybackClusterMediaRewindPayload : NSObject
@end

@interface CHIPMediaPlaybackClusterMediaRewindResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull MediaPlaybackStatus;
@end

@interface CHIPMediaPlaybackClusterMediaFastForwardPayload : NSObject
@end

@interface CHIPMediaPlaybackClusterMediaFastForwardResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull MediaPlaybackStatus;
@end

@interface CHIPMediaPlaybackClusterMediaSkipForwardPayload : NSObject
@property (copy) NSNumber * _Nonnull DeltaPositionMilliseconds;
@end

@interface CHIPMediaPlaybackClusterMediaSkipForwardResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull MediaPlaybackStatus;
@end

@interface CHIPMediaPlaybackClusterMediaSkipBackwardPayload : NSObject
@property (copy) NSNumber * _Nonnull DeltaPositionMilliseconds;
@end

@interface CHIPMediaPlaybackClusterMediaSkipBackwardResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull MediaPlaybackStatus;
@end

@interface CHIPMediaPlaybackClusterMediaSeekPayload : NSObject
@property (copy) NSNumber * _Nonnull Position;
@end

@interface CHIPMediaPlaybackClusterMediaSeekResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull MediaPlaybackStatus;
@end

@interface CHIPMediaInputClusterSelectInputPayload : NSObject
@property (copy) NSNumber * _Nonnull Index;
@end

@interface CHIPMediaInputClusterShowInputStatusPayload : NSObject
@end

@interface CHIPMediaInputClusterHideInputStatusPayload : NSObject
@end

@interface CHIPMediaInputClusterRenameInputPayload : NSObject
@property (copy) NSNumber * _Nonnull Index;
@property (copy) NSString * _Nonnull Name;
@end

@interface CHIPLowPowerClusterSleepPayload : NSObject
@end

@interface CHIPKeypadInputClusterSendKeyPayload : NSObject
@property (copy) NSNumber * _Nonnull KeyCode;
@end

@interface CHIPKeypadInputClusterSendKeyResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPContentLauncherClusterLaunchContentPayload : NSObject
@property (copy) NSNumber * _Nonnull AutoPlay;
@property (copy) NSString * _Nonnull Data;
@end

@interface CHIPContentLauncherClusterLaunchContentResponsePayload : NSObject
@property (copy) NSString * _Nonnull Data;
@property (copy) NSNumber * _Nonnull ContentLaunchStatus;
@end

@interface CHIPContentLauncherClusterLaunchURLPayload : NSObject
@property (copy) NSString * _Nonnull ContentURL;
@property (copy) NSString * _Nonnull DisplayString;
@end

@interface CHIPContentLauncherClusterLaunchURLResponsePayload : NSObject
@property (copy) NSString * _Nonnull Data;
@property (copy) NSNumber * _Nonnull ContentLaunchStatus;
@end

@interface CHIPAudioOutputClusterSelectOutputPayload : NSObject
@property (copy) NSNumber * _Nonnull Index;
@end

@interface CHIPAudioOutputClusterRenameOutputPayload : NSObject
@property (copy) NSNumber * _Nonnull Index;
@property (copy) NSString * _Nonnull Name;
@end

@interface CHIPApplicationLauncherClusterLaunchAppPayload : NSObject
@property (copy) NSString * _Nonnull Data;
@property (copy) NSNumber * _Nonnull CatalogVendorId;
@property (copy) NSString * _Nonnull ApplicationId;
@end

@interface CHIPApplicationLauncherClusterLaunchAppResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSString * _Nonnull Data;
@end

@interface CHIPApplicationBasicClusterChangeStatusPayload : NSObject
@property (copy) NSNumber * _Nonnull Status;
@end

@interface CHIPAccountLoginClusterGetSetupPINPayload : NSObject
@property (copy) NSString * _Nonnull TempAccountIdentifier;
@end

@interface CHIPAccountLoginClusterGetSetupPINResponsePayload : NSObject
@property (copy) NSString * _Nonnull SetupPIN;
@end

@interface CHIPAccountLoginClusterLoginPayload : NSObject
@property (copy) NSString * _Nonnull TempAccountIdentifier;
@property (copy) NSString * _Nonnull SetupPIN;
@end

@interface CHIPTestClusterClusterTestPayload : NSObject
@end

@interface CHIPTestClusterClusterTestSpecificResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ReturnValue;
@end

@interface CHIPTestClusterClusterTestNotHandledPayload : NSObject
@end

@interface CHIPTestClusterClusterTestAddArgumentsResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ReturnValue;
@end

@interface CHIPTestClusterClusterTestSpecificPayload : NSObject
@end

@interface CHIPTestClusterClusterTestSimpleArgumentResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull ReturnValue;
@end

@interface CHIPTestClusterClusterTestUnknownCommandPayload : NSObject
@end

@interface CHIPTestClusterClusterTestStructArrayArgumentResponsePayload : NSObject
@property (copy) NSArray * _Nonnull Arg1;
@property (copy) NSArray * _Nonnull Arg2;
@property (copy) NSArray * _Nonnull Arg3;
@property (copy) NSArray * _Nonnull Arg4;
@property (copy) NSNumber * _Nonnull Arg5;
@property (copy) NSNumber * _Nonnull Arg6;
@end

@interface CHIPTestClusterClusterTestAddArgumentsPayload : NSObject
@property (copy) NSNumber * _Nonnull Arg1;
@property (copy) NSNumber * _Nonnull Arg2;
@end

@interface CHIPTestClusterClusterTestListInt8UReverseResponsePayload : NSObject
@property (copy) NSArray * _Nonnull Arg1;
@end

@interface CHIPTestClusterClusterTestSimpleArgumentRequestPayload : NSObject
@property (copy) NSNumber * _Nonnull Arg1;
@end

@interface CHIPTestClusterClusterTestEnumsResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Arg1;
@property (copy) NSNumber * _Nonnull Arg2;
@end

@interface CHIPTestClusterClusterTestStructArrayArgumentRequestPayload : NSObject
@property (copy) NSArray * _Nonnull Arg1;
@property (copy) NSArray * _Nonnull Arg2;
@property (copy) NSArray * _Nonnull Arg3;
@property (copy) NSArray * _Nonnull Arg4;
@property (copy) NSNumber * _Nonnull Arg5;
@property (copy) NSNumber * _Nonnull Arg6;
@end

@interface CHIPTestClusterClusterTestNullableOptionalResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull WasPresent;
@property (copy) NSNumber * _Nullable WasNull;
@property (copy) NSNumber * _Nullable Value;
@property (copy) NSNumber * _Nullable OriginalValue;
@end

@interface CHIPTestClusterClusterTestStructArgumentRequestPayload : NSObject
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nonnull Arg1;
@end

@interface CHIPTestClusterClusterTestComplexNullableOptionalResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull NullableIntWasNull;
@property (copy) NSNumber * _Nullable NullableIntValue;
@property (copy) NSNumber * _Nonnull OptionalIntWasPresent;
@property (copy) NSNumber * _Nullable OptionalIntValue;
@property (copy) NSNumber * _Nonnull NullableOptionalIntWasPresent;
@property (copy) NSNumber * _Nullable NullableOptionalIntWasNull;
@property (copy) NSNumber * _Nullable NullableOptionalIntValue;
@property (copy) NSNumber * _Nonnull NullableStringWasNull;
@property (copy) NSString * _Nullable NullableStringValue;
@property (copy) NSNumber * _Nonnull OptionalStringWasPresent;
@property (copy) NSString * _Nullable OptionalStringValue;
@property (copy) NSNumber * _Nonnull NullableOptionalStringWasPresent;
@property (copy) NSNumber * _Nullable NullableOptionalStringWasNull;
@property (copy) NSString * _Nullable NullableOptionalStringValue;
@property (copy) NSNumber * _Nonnull NullableStructWasNull;
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nullable NullableStructValue;
@property (copy) NSNumber * _Nonnull OptionalStructWasPresent;
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nullable OptionalStructValue;
@property (copy) NSNumber * _Nonnull NullableOptionalStructWasPresent;
@property (copy) NSNumber * _Nullable NullableOptionalStructWasNull;
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nullable NullableOptionalStructValue;
@property (copy) NSNumber * _Nonnull NullableListWasNull;
@property (copy) NSArray * _Nullable NullableListValue;
@property (copy) NSNumber * _Nonnull OptionalListWasPresent;
@property (copy) NSArray * _Nullable OptionalListValue;
@property (copy) NSNumber * _Nonnull NullableOptionalListWasPresent;
@property (copy) NSNumber * _Nullable NullableOptionalListWasNull;
@property (copy) NSArray * _Nullable NullableOptionalListValue;
@end

@interface CHIPTestClusterClusterTestNestedStructArgumentRequestPayload : NSObject
@property (copy) CHIPTestClusterClusterNestedStruct * _Nonnull Arg1;
@end

@interface CHIPTestClusterClusterBooleanResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull Value;
@end

@interface CHIPTestClusterClusterTestListStructArgumentRequestPayload : NSObject
@property (copy) NSArray * _Nonnull Arg1;
@end

@interface CHIPTestClusterClusterTestListInt8UArgumentRequestPayload : NSObject
@property (copy) NSArray * _Nonnull Arg1;
@end

@interface CHIPTestClusterClusterTestNestedStructListArgumentRequestPayload : NSObject
@property (copy) CHIPTestClusterClusterNestedStructList * _Nonnull Arg1;
@end

@interface CHIPTestClusterClusterTestListNestedStructListArgumentRequestPayload : NSObject
@property (copy) NSArray * _Nonnull Arg1;
@end

@interface CHIPTestClusterClusterTestListInt8UReverseRequestPayload : NSObject
@property (copy) NSArray * _Nonnull Arg1;
@end

@interface CHIPTestClusterClusterTestEnumsRequestPayload : NSObject
@property (copy) NSNumber * _Nonnull Arg1;
@property (copy) NSNumber * _Nonnull Arg2;
@end

@interface CHIPTestClusterClusterTestNullableOptionalRequestPayload : NSObject
@property (copy) NSNumber * _Nullable Arg1;
@end

@interface CHIPTestClusterClusterTestComplexNullableOptionalRequestPayload : NSObject
@property (copy) NSNumber * _Nullable NullableInt;
@property (copy) NSNumber * _Nullable OptionalInt;
@property (copy) NSNumber * _Nullable NullableOptionalInt;
@property (copy) NSString * _Nullable NullableString;
@property (copy) NSString * _Nullable OptionalString;
@property (copy) NSString * _Nullable NullableOptionalString;
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nullable NullableStruct;
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nullable OptionalStruct;
@property (copy) CHIPTestClusterClusterSimpleStruct * _Nullable NullableOptionalStruct;
@property (copy) NSArray * _Nullable NullableList;
@property (copy) NSArray * _Nullable OptionalList;
@property (copy) NSArray * _Nullable NullableOptionalList;
@end

@interface CHIPMessagingClusterDisplayMessagePayload : NSObject
@property (copy) NSNumber * _Nonnull MessageId;
@property (copy) NSNumber * _Nonnull MessageControl;
@property (copy) NSNumber * _Nonnull StartTime;
@property (copy) NSNumber * _Nonnull DurationInMinutes;
@property (copy) NSString * _Nonnull Message;
@property (copy) NSNumber * _Nonnull OptionalExtendedMessageControl;
@end

@interface CHIPMessagingClusterGetLastMessagePayload : NSObject
@end

@interface CHIPMessagingClusterCancelMessagePayload : NSObject
@property (copy) NSNumber * _Nonnull MessageId;
@property (copy) NSNumber * _Nonnull MessageControl;
@end

@interface CHIPMessagingClusterMessageConfirmationPayload : NSObject
@property (copy) NSNumber * _Nonnull MessageId;
@property (copy) NSNumber * _Nonnull ConfirmationTime;
@property (copy) NSNumber * _Nonnull MessageConfirmationControl;
@property (copy) NSData * _Nonnull MessageResponse;
@end

@interface CHIPMessagingClusterDisplayProtectedMessagePayload : NSObject
@property (copy) NSNumber * _Nonnull MessageId;
@property (copy) NSNumber * _Nonnull MessageControl;
@property (copy) NSNumber * _Nonnull StartTime;
@property (copy) NSNumber * _Nonnull DurationInMinutes;
@property (copy) NSString * _Nonnull Message;
@property (copy) NSNumber * _Nonnull OptionalExtendedMessageControl;
@end

@interface CHIPMessagingClusterGetMessageCancellationPayload : NSObject
@property (copy) NSNumber * _Nonnull EarliestImplementationTime;
@end

@interface CHIPMessagingClusterCancelAllMessagesPayload : NSObject
@property (copy) NSNumber * _Nonnull ImplementationDateTime;
@end

@interface CHIPApplianceEventsAndAlertClusterGetAlertsPayload : NSObject
@end

@interface CHIPApplianceEventsAndAlertClusterGetAlertsResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull AlertsCount;
@property (copy) NSArray * _Nonnull AlertStructures;
@end

@interface CHIPApplianceEventsAndAlertClusterAlertsNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull AlertsCount;
@property (copy) NSArray * _Nonnull AlertStructures;
@end

@interface CHIPApplianceEventsAndAlertClusterEventsNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull EventHeader;
@property (copy) NSNumber * _Nonnull EventId;
@end

@interface CHIPApplianceStatisticsClusterLogNotificationPayload : NSObject
@property (copy) NSNumber * _Nonnull TimeStamp;
@property (copy) NSNumber * _Nonnull LogId;
@property (copy) NSNumber * _Nonnull LogLength;
@property (copy) NSArray * _Nonnull LogPayload;
@end

@interface CHIPApplianceStatisticsClusterLogRequestPayload : NSObject
@property (copy) NSNumber * _Nonnull LogId;
@end

@interface CHIPApplianceStatisticsClusterLogResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull TimeStamp;
@property (copy) NSNumber * _Nonnull LogId;
@property (copy) NSNumber * _Nonnull LogLength;
@property (copy) NSArray * _Nonnull LogPayload;
@end

@interface CHIPApplianceStatisticsClusterLogQueueRequestPayload : NSObject
@end

@interface CHIPApplianceStatisticsClusterLogQueueResponsePayload : NSObject
@property (copy) NSNumber * _Nonnull LogQueueSize;
@property (copy) NSArray * _Nonnull LogIds;
@end

@interface CHIPApplianceStatisticsClusterStatisticsAvailablePayload : NSObject
@property (copy) NSNumber * _Nonnull LogQueueSize;
@property (copy) NSArray * _Nonnull LogIds;
@end

@interface CHIPElectricalMeasurementClusterGetProfileInfoResponseCommandPayload : NSObject
@property (copy) NSNumber * _Nonnull ProfileCount;
@property (copy) NSNumber * _Nonnull ProfileIntervalPeriod;
@property (copy) NSNumber * _Nonnull MaxNumberOfIntervals;
@property (copy) NSArray * _Nonnull ListOfAttributes;
@end

@interface CHIPElectricalMeasurementClusterGetProfileInfoCommandPayload : NSObject
@end

@interface CHIPElectricalMeasurementClusterGetMeasurementProfileResponseCommandPayload : NSObject
@property (copy) NSNumber * _Nonnull StartTime;
@property (copy) NSNumber * _Nonnull Status;
@property (copy) NSNumber * _Nonnull ProfileIntervalPeriod;
@property (copy) NSNumber * _Nonnull NumberOfIntervalsDelivered;
@property (copy) NSNumber * _Nonnull AttributeId;
@property (copy) NSArray * _Nonnull Intervals;
@end

@interface CHIPElectricalMeasurementClusterGetMeasurementProfileCommandPayload : NSObject
@property (copy) NSNumber * _Nonnull AttributeId;
@property (copy) NSNumber * _Nonnull StartTime;
@property (copy) NSNumber * _Nonnull NumberOfIntervals;
@end

@interface CHIPBindingClusterBindPayload : NSObject
@property (copy) NSNumber * _Nonnull NodeId;
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull EndpointId;
@property (copy) NSNumber * _Nonnull ClusterId;
@end

@interface CHIPBindingClusterUnbindPayload : NSObject
@property (copy) NSNumber * _Nonnull NodeId;
@property (copy) NSNumber * _Nonnull GroupId;
@property (copy) NSNumber * _Nonnull EndpointId;
@property (copy) NSNumber * _Nonnull ClusterId;
@end

@interface CHIPSampleMfgSpecificClusterClusterCommandOnePayload : NSObject
@property (copy) NSNumber * _Nonnull ArgOne;
@end

@interface CHIPSampleMfgSpecificCluster2ClusterCommandTwoPayload : NSObject
@property (copy) NSNumber * _Nonnull ArgOne;
@end

#endif /* CHIP_COMMAND_PAYLOADS_H */
